// Auto-generated by extract.js — 2026-05-08T10:45:21.405Z
const YOM_DATA = {
  "extractedAt": "2026-05-08T10:38:24.070Z",
  "fxRates": {
    "CLP_TO_USD": 0.00111914,
    "COP_TO_USD": 0.0002699
  },
  "clients": [
    {
      "domain": "soprole.youorder.me",
      "name": "Soprole",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 194881,
      "comercios": 10613,
      "comerciosRegistrados": 246513,
      "vendedores": 239,
      "vendedoresYOM": 8,
      "cuentasVendedor": 263,
      "ventaSinIVA": 40981196,
      "primeraOrden": "2021-02-09T19:52:52.720Z",
      "ultimaOrden": "2026-05-08T04:38:28.865Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 4920,
          "ventaSinIVA": 987900,
          "comerciosActivos": 2372,
          "vendedoresActivos": 181
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 6350,
          "ventaSinIVA": 1240296,
          "comerciosActivos": 2664,
          "vendedoresActivos": 185
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 7252,
          "ventaSinIVA": 1488303,
          "comerciosActivos": 2836,
          "vendedoresActivos": 188
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 7259,
          "ventaSinIVA": 1438321,
          "comerciosActivos": 2914,
          "vendedoresActivos": 211
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 6799,
          "ventaSinIVA": 1462464,
          "comerciosActivos": 2909,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 7548,
          "ventaSinIVA": 1479386,
          "comerciosActivos": 2914,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 6962,
          "ventaSinIVA": 1391794,
          "comerciosActivos": 2851,
          "vendedoresActivos": 212
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 6819,
          "ventaSinIVA": 1371479,
          "comerciosActivos": 2819,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 7121,
          "ventaSinIVA": 1388181,
          "comerciosActivos": 2931,
          "vendedoresActivos": 219
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6833,
          "ventaSinIVA": 1387332,
          "comerciosActivos": 2954,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 7866,
          "ventaSinIVA": 1485293,
          "comerciosActivos": 3061,
          "vendedoresActivos": 221
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 7369,
          "ventaSinIVA": 1441158,
          "comerciosActivos": 2988,
          "vendedoresActivos": 227
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 1688,
          "ventaSinIVA": 329984,
          "comerciosActivos": 1609,
          "vendedoresActivos": 223
        }
      ]
    },
    {
      "domain": "codelpa.youorder.me",
      "name": "Codelpa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 120798,
      "comercios": 2825,
      "comerciosRegistrados": 6891,
      "vendedores": 34,
      "vendedoresYOM": 22,
      "cuentasVendedor": 857,
      "ventaSinIVA": 152569428,
      "primeraOrden": "2020-06-01T20:36:18.883Z",
      "ultimaOrden": "2026-05-07T23:06:00.999Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 997,
          "ventaSinIVA": 1294535,
          "comerciosActivos": 564,
          "vendedoresActivos": 23
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 1256,
          "ventaSinIVA": 1596992,
          "comerciosActivos": 628,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1467,
          "ventaSinIVA": 2088752,
          "comerciosActivos": 719,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1585,
          "ventaSinIVA": 2443864,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1536,
          "ventaSinIVA": 1857829,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 1806,
          "ventaSinIVA": 2398421,
          "comerciosActivos": 773,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 1802,
          "ventaSinIVA": 2602160,
          "comerciosActivos": 769,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 1801,
          "ventaSinIVA": 2565268,
          "comerciosActivos": 768,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 1797,
          "ventaSinIVA": 2680010,
          "comerciosActivos": 733,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1559,
          "ventaSinIVA": 2350016,
          "comerciosActivos": 687,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1872,
          "ventaSinIVA": 2941899,
          "comerciosActivos": 774,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1583,
          "ventaSinIVA": 2555513,
          "comerciosActivos": 719,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 218,
          "ventaSinIVA": 285956,
          "comerciosActivos": 181,
          "vendedoresActivos": 22
        }
      ]
    },
    {
      "domain": "codelpa-peru.youorder.me",
      "name": "Codelpa Perú",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "softys-cencocal.youorder.me",
      "name": "Softys-Cencocal",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 928731,
      "comercios": 18433,
      "comerciosRegistrados": 28996,
      "vendedores": 79,
      "vendedoresYOM": 2,
      "cuentasVendedor": 59,
      "ventaSinIVA": 74931484,
      "primeraOrden": "2021-10-14T16:10:20.000Z",
      "ultimaOrden": "2026-05-07T21:58:38.871Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 16854,
          "ventaSinIVA": 1389046,
          "comerciosActivos": 8859,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 20459,
          "ventaSinIVA": 1695022,
          "comerciosActivos": 9406,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 22245,
          "ventaSinIVA": 1809500,
          "comerciosActivos": 9615,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 20703,
          "ventaSinIVA": 1716684,
          "comerciosActivos": 9602,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 20331,
          "ventaSinIVA": 1779558,
          "comerciosActivos": 9369,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 22245,
          "ventaSinIVA": 1760295,
          "comerciosActivos": 9460,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 19517,
          "ventaSinIVA": 1515202,
          "comerciosActivos": 9392,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 20442,
          "ventaSinIVA": 1720808,
          "comerciosActivos": 9301,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 20863,
          "ventaSinIVA": 1812367,
          "comerciosActivos": 9503,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 18629,
          "ventaSinIVA": 1625609,
          "comerciosActivos": 8890,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 20520,
          "ventaSinIVA": 1679099,
          "comerciosActivos": 9330,
          "vendedoresActivos": 49
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 18879,
          "ventaSinIVA": 1555881,
          "comerciosActivos": 9085,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 3995,
          "ventaSinIVA": 320237,
          "comerciosActivos": 3917,
          "vendedoresActivos": 49
        }
      ]
    },
    {
      "domain": "softys-dimak.youorder.me",
      "name": "Dimak",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "surtiventas.youorder.me",
      "name": "Surtiventas",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 99325,
      "comercios": 10817,
      "comerciosRegistrados": 11346,
      "vendedores": 77,
      "vendedoresYOM": 2,
      "cuentasVendedor": 93,
      "ventaSinIVA": 30010163,
      "primeraOrden": "2025-06-18T15:17:44.387Z",
      "ultimaOrden": "2026-05-08T07:08:07.702Z",
      "mensual": [
        {
          "year": 2025,
          "month": 6,
          "ordenes": 75,
          "ventaSinIVA": 68208,
          "comerciosActivos": 71,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 967,
          "ventaSinIVA": 95528,
          "comerciosActivos": 764,
          "vendedoresActivos": 5
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1122,
          "ventaSinIVA": 247389,
          "comerciosActivos": 648,
          "vendedoresActivos": 12
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 3506,
          "ventaSinIVA": 887675,
          "comerciosActivos": 2155,
          "vendedoresActivos": 32
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 9846,
          "ventaSinIVA": 2046757,
          "comerciosActivos": 5136,
          "vendedoresActivos": 60
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 11451,
          "ventaSinIVA": 3532458,
          "comerciosActivos": 5807,
          "vendedoresActivos": 63
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 12330,
          "ventaSinIVA": 4372415,
          "comerciosActivos": 6108,
          "vendedoresActivos": 66
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 13151,
          "ventaSinIVA": 5200183,
          "comerciosActivos": 6579,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 12003,
          "ventaSinIVA": 4072982,
          "comerciosActivos": 5903,
          "vendedoresActivos": 65
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 16968,
          "ventaSinIVA": 5172410,
          "comerciosActivos": 7212,
          "vendedoresActivos": 61
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 14940,
          "ventaSinIVA": 3780657,
          "comerciosActivos": 6968,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 2966,
          "ventaSinIVA": 533502,
          "comerciosActivos": 2655,
          "vendedoresActivos": 56
        }
      ]
    },
    {
      "domain": "elmuneco.youorder.me",
      "name": "El Muñeco",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 2832,
      "comercios": 886,
      "comerciosRegistrados": 7636,
      "vendedores": 10,
      "vendedoresYOM": 2,
      "cuentasVendedor": 16,
      "ventaSinIVA": 197558,
      "primeraOrden": "2025-07-02T20:14:49.488Z",
      "ultimaOrden": "2026-05-07T15:05:36.600Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1,
          "ventaSinIVA": 52,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 142,
          "ventaSinIVA": 8934,
          "comerciosActivos": 112,
          "vendedoresActivos": 2
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 16,
          "ventaSinIVA": 770,
          "comerciosActivos": 16,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 4,
          "ventaSinIVA": 136,
          "comerciosActivos": 1,
          "vendedoresActivos": 1
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 8,
          "ventaSinIVA": 667,
          "comerciosActivos": 7,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 30,
          "ventaSinIVA": 2517,
          "comerciosActivos": 25,
          "vendedoresActivos": 3
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 230,
          "ventaSinIVA": 15973,
          "comerciosActivos": 213,
          "vendedoresActivos": 6
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1285,
          "ventaSinIVA": 96507,
          "comerciosActivos": 639,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 762,
          "ventaSinIVA": 52786,
          "comerciosActivos": 469,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 311,
          "ventaSinIVA": 16740,
          "comerciosActivos": 162,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 43,
          "ventaSinIVA": 2476,
          "comerciosActivos": 42,
          "vendedoresActivos": 2
        }
      ]
    },
    {
      "domain": "marleycoffee.youorder.me",
      "name": "Marley Coffee",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 354,
      "comercios": 60,
      "comerciosRegistrados": 2871,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 57,
      "ventaSinIVA": 217790,
      "primeraOrden": "2025-07-15T21:53:35.185Z",
      "ultimaOrden": "2026-05-08T01:48:22.989Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 14,
          "ventaSinIVA": 11207,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 2,
          "ventaSinIVA": 1027,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 2635,
          "comerciosActivos": 3,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 25,
          "ventaSinIVA": 22487,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 49,
          "ventaSinIVA": 34755,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 47,
          "ventaSinIVA": 31299,
          "comerciosActivos": 15,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 30,
          "ventaSinIVA": 20561,
          "comerciosActivos": 14,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 57,
          "ventaSinIVA": 38241,
          "comerciosActivos": 17,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 109,
          "ventaSinIVA": 48814,
          "comerciosActivos": 54,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 18,
          "ventaSinIVA": 6763,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisa.youorder.me",
      "name": "Prisa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "caren.youorder.me",
      "name": "Caren",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "coexito.youorder.me",
      "name": "CoÉxito",
      "currency": "USD",
      "nativeCurrency": "COP",
      "sinDatos": false,
      "ordenes": 29256,
      "comercios": 5609,
      "comerciosRegistrados": 22981,
      "vendedores": 93,
      "vendedoresYOM": 0,
      "cuentasVendedor": 141,
      "ventaSinIVA": 27369922,
      "primeraOrden": "2025-11-12T21:55:34.073Z",
      "ultimaOrden": "2026-05-08T01:47:43.671Z",
      "mensual": [
        {
          "year": 2025,
          "month": 11,
          "ordenes": 34,
          "ventaSinIVA": 21661,
          "comerciosActivos": 23,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 763,
          "ventaSinIVA": 728627,
          "comerciosActivos": 365,
          "vendedoresActivos": 10
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 2278,
          "ventaSinIVA": 2557029,
          "comerciosActivos": 1273,
          "vendedoresActivos": 40
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6794,
          "ventaSinIVA": 6265607,
          "comerciosActivos": 3323,
          "vendedoresActivos": 87
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 9253,
          "ventaSinIVA": 8705261,
          "comerciosActivos": 3721,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 8668,
          "ventaSinIVA": 7978240,
          "comerciosActivos": 3803,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 1466,
          "ventaSinIVA": 1113498,
          "comerciosActivos": 1168,
          "vendedoresActivos": 85
        }
      ]
    },
    {
      "domain": "bastien.youorder.me",
      "name": "Bastien",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "sonrie.youorder.me",
      "name": "Sonrie",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 10,
      "comercios": 3,
      "comerciosRegistrados": 2167,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 1,
      "ventaSinIVA": 188,
      "primeraOrden": "2025-09-30T18:05:34.310Z",
      "ultimaOrden": "2026-04-23T19:05:57.930Z",
      "mensual": [
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1,
          "ventaSinIVA": 12,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 76,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 6,
          "ventaSinIVA": 100,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "expressdent.youorder.me",
      "name": "ExpressDent",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 6,
      "comercios": 4,
      "comerciosRegistrados": 13568,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 31,
      "ventaSinIVA": 103,
      "primeraOrden": "2026-01-06T19:43:36.968Z",
      "ultimaOrden": "2026-02-05T19:56:42.097Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 5,
          "ventaSinIVA": 102,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1,
          "ventaSinIVA": 1,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisur.youorder.me",
      "name": "Prisur",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 4125,
      "comercios": 1381,
      "comerciosRegistrados": 10794,
      "vendedores": 33,
      "vendedoresYOM": 2,
      "cuentasVendedor": 44,
      "ventaSinIVA": 610306,
      "primeraOrden": "2026-01-20T14:59:35.680Z",
      "ultimaOrden": "2026-05-07T23:14:18.133Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 89,
          "ventaSinIVA": 10425,
          "comerciosActivos": 64,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1034,
          "ventaSinIVA": 151200,
          "comerciosActivos": 665,
          "vendedoresActivos": 24
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1614,
          "ventaSinIVA": 246728,
          "comerciosActivos": 843,
          "vendedoresActivos": 20
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1179,
          "ventaSinIVA": 171822,
          "comerciosActivos": 749,
          "vendedoresActivos": 21
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 209,
          "ventaSinIVA": 30131,
          "comerciosActivos": 195,
          "vendedoresActivos": 11
        }
      ]
    }
  ]
};
