// Auto-generated by extract.js — 2026-05-02T10:30:34.013Z
const YOM_DATA = {
  "extractedAt": "2026-05-02T10:24:06.450Z",
  "fxRates": {
    "CLP_TO_USD": 0.00110159,
    "COP_TO_USD": 0.00027582
  },
  "clients": [
    {
      "domain": "soprole.youorder.me",
      "name": "Soprole",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 193287,
      "comercios": 10572,
      "comerciosRegistrados": 246199,
      "vendedores": 239,
      "vendedoresYOM": 8,
      "cuentasVendedor": 263,
      "ventaSinIVA": 40029902,
      "primeraOrden": "2021-02-09T19:52:52.720Z",
      "ultimaOrden": "2026-05-02T07:34:05.675Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 6215,
          "ventaSinIVA": 1260733,
          "comerciosActivos": 2539,
          "vendedoresActivos": 182
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 6350,
          "ventaSinIVA": 1220846,
          "comerciosActivos": 2664,
          "vendedoresActivos": 185
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 7252,
          "ventaSinIVA": 1464964,
          "comerciosActivos": 2836,
          "vendedoresActivos": 188
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 7259,
          "ventaSinIVA": 1415765,
          "comerciosActivos": 2914,
          "vendedoresActivos": 211
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 6799,
          "ventaSinIVA": 1439530,
          "comerciosActivos": 2909,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 7548,
          "ventaSinIVA": 1456187,
          "comerciosActivos": 2914,
          "vendedoresActivos": 210
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 6962,
          "ventaSinIVA": 1369968,
          "comerciosActivos": 2851,
          "vendedoresActivos": 212
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 6819,
          "ventaSinIVA": 1349972,
          "comerciosActivos": 2819,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 7121,
          "ventaSinIVA": 1366412,
          "comerciosActivos": 2931,
          "vendedoresActivos": 219
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6833,
          "ventaSinIVA": 1365577,
          "comerciosActivos": 2954,
          "vendedoresActivos": 218
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 7866,
          "ventaSinIVA": 1462001,
          "comerciosActivos": 3061,
          "vendedoresActivos": 221
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 7369,
          "ventaSinIVA": 1418559,
          "comerciosActivos": 2988,
          "vendedoresActivos": 227
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 94,
          "ventaSinIVA": 16169,
          "comerciosActivos": 93,
          "vendedoresActivos": 78
        }
      ]
    },
    {
      "domain": "codelpa.youorder.me",
      "name": "Codelpa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 120576,
      "comercios": 2824,
      "comerciosRegistrados": 6884,
      "vendedores": 34,
      "vendedoresYOM": 22,
      "cuentasVendedor": 855,
      "ventaSinIVA": 149892450,
      "primeraOrden": "2020-06-01T20:36:18.883Z",
      "ultimaOrden": "2026-04-30T23:48:50.777Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 1036,
          "ventaSinIVA": 1304473,
          "comerciosActivos": 581,
          "vendedoresActivos": 23
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 1256,
          "ventaSinIVA": 1571949,
          "comerciosActivos": 628,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1467,
          "ventaSinIVA": 2055997,
          "comerciosActivos": 719,
          "vendedoresActivos": 24
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1585,
          "ventaSinIVA": 2405540,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1536,
          "ventaSinIVA": 1828696,
          "comerciosActivos": 741,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 1806,
          "ventaSinIVA": 2360810,
          "comerciosActivos": 773,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 1802,
          "ventaSinIVA": 2561354,
          "comerciosActivos": 769,
          "vendedoresActivos": 22
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 1801,
          "ventaSinIVA": 2525041,
          "comerciosActivos": 768,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 1797,
          "ventaSinIVA": 2637983,
          "comerciosActivos": 733,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1559,
          "ventaSinIVA": 2313163,
          "comerciosActivos": 687,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1872,
          "ventaSinIVA": 2895765,
          "comerciosActivos": 774,
          "vendedoresActivos": 22
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1579,
          "ventaSinIVA": 2512477,
          "comerciosActivos": 718,
          "vendedoresActivos": 22
        }
      ]
    },
    {
      "domain": "codelpa-peru.youorder.me",
      "name": "Codelpa Perú",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "softys-cencocal.youorder.me",
      "name": "Softys-Cencocal",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 924736,
      "comercios": 18405,
      "comerciosRegistrados": 28963,
      "vendedores": 79,
      "vendedoresYOM": 2,
      "cuentasVendedor": 59,
      "ventaSinIVA": 73441217,
      "primeraOrden": "2021-10-14T16:10:20.000Z",
      "ultimaOrden": "2026-04-30T18:04:57.003Z",
      "mensual": [
        {
          "year": 2025,
          "month": 5,
          "ordenes": 21010,
          "ventaSinIVA": 1750229,
          "comerciosActivos": 9490,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 6,
          "ordenes": 20459,
          "ventaSinIVA": 1668441,
          "comerciosActivos": 9406,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 22245,
          "ventaSinIVA": 1781124,
          "comerciosActivos": 9615,
          "vendedoresActivos": 51
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 20703,
          "ventaSinIVA": 1689764,
          "comerciosActivos": 9602,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 20331,
          "ventaSinIVA": 1751651,
          "comerciosActivos": 9369,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 22245,
          "ventaSinIVA": 1732691,
          "comerciosActivos": 9460,
          "vendedoresActivos": 49
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 19517,
          "ventaSinIVA": 1491441,
          "comerciosActivos": 9392,
          "vendedoresActivos": 50
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 20442,
          "ventaSinIVA": 1693823,
          "comerciosActivos": 9301,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 20863,
          "ventaSinIVA": 1783946,
          "comerciosActivos": 9503,
          "vendedoresActivos": 51
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 18629,
          "ventaSinIVA": 1600117,
          "comerciosActivos": 8890,
          "vendedoresActivos": 50
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 20520,
          "ventaSinIVA": 1652768,
          "comerciosActivos": 9330,
          "vendedoresActivos": 49
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 18879,
          "ventaSinIVA": 1531482,
          "comerciosActivos": 9085,
          "vendedoresActivos": 51
        }
      ]
    },
    {
      "domain": "softys-dimak.youorder.me",
      "name": "Dimak",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "surtiventas.youorder.me",
      "name": "Surtiventas",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 96375,
      "comercios": 10754,
      "comerciosRegistrados": 11258,
      "vendedores": 77,
      "vendedoresYOM": 2,
      "cuentasVendedor": 91,
      "ventaSinIVA": 29017467,
      "primeraOrden": "2025-06-18T15:17:44.387Z",
      "ultimaOrden": "2026-05-02T04:19:39.063Z",
      "mensual": [
        {
          "year": 2025,
          "month": 6,
          "ordenes": 75,
          "ventaSinIVA": 67138,
          "comerciosActivos": 71,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 7,
          "ordenes": 967,
          "ventaSinIVA": 94030,
          "comerciosActivos": 764,
          "vendedoresActivos": 5
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 1122,
          "ventaSinIVA": 243510,
          "comerciosActivos": 648,
          "vendedoresActivos": 12
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 3506,
          "ventaSinIVA": 873755,
          "comerciosActivos": 2155,
          "vendedoresActivos": 32
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 9846,
          "ventaSinIVA": 2014660,
          "comerciosActivos": 5136,
          "vendedoresActivos": 60
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 11451,
          "ventaSinIVA": 3477063,
          "comerciosActivos": 5807,
          "vendedoresActivos": 63
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 12330,
          "ventaSinIVA": 4303848,
          "comerciosActivos": 6108,
          "vendedoresActivos": 66
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 13151,
          "ventaSinIVA": 5118635,
          "comerciosActivos": 6579,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 12003,
          "ventaSinIVA": 4009111,
          "comerciosActivos": 5903,
          "vendedoresActivos": 65
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 16968,
          "ventaSinIVA": 5091298,
          "comerciosActivos": 7212,
          "vendedoresActivos": 61
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 14940,
          "ventaSinIVA": 3721370,
          "comerciosActivos": 6968,
          "vendedoresActivos": 63
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 16,
          "ventaSinIVA": 3049,
          "comerciosActivos": 16,
          "vendedoresActivos": 5
        }
      ]
    },
    {
      "domain": "elmuneco.youorder.me",
      "name": "El Muñeco",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 2789,
      "comercios": 883,
      "comerciosRegistrados": 7626,
      "vendedores": 10,
      "vendedoresYOM": 2,
      "cuentasVendedor": 16,
      "ventaSinIVA": 192023,
      "primeraOrden": "2025-07-02T20:14:49.488Z",
      "ultimaOrden": "2026-04-30T18:37:04.901Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 1,
          "ventaSinIVA": 51,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 8,
          "ordenes": 142,
          "ventaSinIVA": 8794,
          "comerciosActivos": 112,
          "vendedoresActivos": 2
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 16,
          "ventaSinIVA": 758,
          "comerciosActivos": 16,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 4,
          "ventaSinIVA": 134,
          "comerciosActivos": 1,
          "vendedoresActivos": 1
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 8,
          "ventaSinIVA": 656,
          "comerciosActivos": 7,
          "vendedoresActivos": 3
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 30,
          "ventaSinIVA": 2478,
          "comerciosActivos": 25,
          "vendedoresActivos": 3
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 230,
          "ventaSinIVA": 15722,
          "comerciosActivos": 213,
          "vendedoresActivos": 6
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1285,
          "ventaSinIVA": 94994,
          "comerciosActivos": 639,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 762,
          "ventaSinIVA": 51958,
          "comerciosActivos": 469,
          "vendedoresActivos": 8
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 311,
          "ventaSinIVA": 16477,
          "comerciosActivos": 162,
          "vendedoresActivos": 2
        }
      ]
    },
    {
      "domain": "marleycoffee.youorder.me",
      "name": "Marley Coffee",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 336,
      "comercios": 59,
      "comerciosRegistrados": 2854,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 57,
      "ventaSinIVA": 207718,
      "primeraOrden": "2025-07-15T21:53:35.185Z",
      "ultimaOrden": "2026-04-30T20:41:46.917Z",
      "mensual": [
        {
          "year": 2025,
          "month": 7,
          "ordenes": 14,
          "ventaSinIVA": 11032,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 9,
          "ordenes": 2,
          "ventaSinIVA": 1011,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 2594,
          "comerciosActivos": 3,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 11,
          "ordenes": 25,
          "ventaSinIVA": 22134,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 49,
          "ventaSinIVA": 34210,
          "comerciosActivos": 13,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 47,
          "ventaSinIVA": 30809,
          "comerciosActivos": 15,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 30,
          "ventaSinIVA": 20239,
          "comerciosActivos": 14,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 57,
          "ventaSinIVA": 37642,
          "comerciosActivos": 17,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 109,
          "ventaSinIVA": 48048,
          "comerciosActivos": 54,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisa.youorder.me",
      "name": "Prisa",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "caren.youorder.me",
      "name": "Caren",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "coexito.youorder.me",
      "name": "CoÉxito",
      "currency": "USD",
      "nativeCurrency": "COP",
      "sinDatos": false,
      "ordenes": 27807,
      "comercios": 5528,
      "comerciosRegistrados": 22937,
      "vendedores": 92,
      "vendedoresYOM": 0,
      "cuentasVendedor": 141,
      "ventaSinIVA": 26876549,
      "primeraOrden": "2025-11-12T21:55:34.073Z",
      "ultimaOrden": "2026-05-01T12:43:07.033Z",
      "mensual": [
        {
          "year": 2025,
          "month": 11,
          "ordenes": 34,
          "ventaSinIVA": 22136,
          "comerciosActivos": 23,
          "vendedoresActivos": 4
        },
        {
          "year": 2025,
          "month": 12,
          "ordenes": 763,
          "ventaSinIVA": 744609,
          "comerciosActivos": 365,
          "vendedoresActivos": 10
        },
        {
          "year": 2026,
          "month": 1,
          "ordenes": 2278,
          "ventaSinIVA": 2613115,
          "comerciosActivos": 1273,
          "vendedoresActivos": 40
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 6794,
          "ventaSinIVA": 6403038,
          "comerciosActivos": 3323,
          "vendedoresActivos": 87
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 9253,
          "ventaSinIVA": 8896202,
          "comerciosActivos": 3721,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 8668,
          "ventaSinIVA": 8153235,
          "comerciosActivos": 3803,
          "vendedoresActivos": 85
        },
        {
          "year": 2026,
          "month": 5,
          "ordenes": 17,
          "ventaSinIVA": 44215,
          "comerciosActivos": 17,
          "vendedoresActivos": 7
        }
      ]
    },
    {
      "domain": "bastien.youorder.me",
      "name": "Bastien",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": true,
      "ordenes": 0,
      "comercios": 0,
      "comerciosRegistrados": 0,
      "ventaSinIVA": 0,
      "primeraOrden": null,
      "ultimaOrden": null,
      "mensual": []
    },
    {
      "domain": "sonrie.youorder.me",
      "name": "Sonrie",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 10,
      "comercios": 3,
      "comerciosRegistrados": 2166,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 1,
      "ventaSinIVA": 185,
      "primeraOrden": "2025-09-30T18:05:34.310Z",
      "ultimaOrden": "2026-04-23T19:05:57.930Z",
      "mensual": [
        {
          "year": 2025,
          "month": 9,
          "ordenes": 1,
          "ventaSinIVA": 11,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        },
        {
          "year": 2025,
          "month": 10,
          "ordenes": 3,
          "ventaSinIVA": 75,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 6,
          "ventaSinIVA": 98,
          "comerciosActivos": 2,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "expressdent.youorder.me",
      "name": "ExpressDent",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 6,
      "comercios": 4,
      "comerciosRegistrados": 13566,
      "vendedores": 0,
      "vendedoresYOM": 1,
      "cuentasVendedor": 30,
      "ventaSinIVA": 101,
      "primeraOrden": "2026-01-06T19:43:36.968Z",
      "ultimaOrden": "2026-02-05T19:56:42.097Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 5,
          "ventaSinIVA": 100,
          "comerciosActivos": 4,
          "vendedoresActivos": 0
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1,
          "ventaSinIVA": 1,
          "comerciosActivos": 1,
          "vendedoresActivos": 0
        }
      ]
    },
    {
      "domain": "prisur.youorder.me",
      "name": "Prisur",
      "currency": "USD",
      "nativeCurrency": "CLP",
      "sinDatos": false,
      "ordenes": 3916,
      "comercios": 1349,
      "comerciosRegistrados": 10776,
      "vendedores": 32,
      "vendedoresYOM": 2,
      "cuentasVendedor": 44,
      "ventaSinIVA": 571077,
      "primeraOrden": "2026-01-20T14:59:35.680Z",
      "ultimaOrden": "2026-04-30T23:01:50.982Z",
      "mensual": [
        {
          "year": 2026,
          "month": 1,
          "ordenes": 89,
          "ventaSinIVA": 10261,
          "comerciosActivos": 64,
          "vendedoresActivos": 2
        },
        {
          "year": 2026,
          "month": 2,
          "ordenes": 1034,
          "ventaSinIVA": 148829,
          "comerciosActivos": 665,
          "vendedoresActivos": 24
        },
        {
          "year": 2026,
          "month": 3,
          "ordenes": 1614,
          "ventaSinIVA": 242859,
          "comerciosActivos": 843,
          "vendedoresActivos": 20
        },
        {
          "year": 2026,
          "month": 4,
          "ordenes": 1179,
          "ventaSinIVA": 169128,
          "comerciosActivos": 749,
          "vendedoresActivos": 21
        }
      ]
    }
  ]
};
